### ISSUE TITLE
Critical startup error when two plugin versions are installed

### ISSUE THREAD

**Issue by intgr** [nhat-phan/merge-request-integration#20] opened 2020-01-31 08:56 UTC
First installed the plugin for CE, restarted IntelliJ, which worked. Then after installing the GitLab EE plugin, I was greeted with the following error on startup:

<pre>
Internal error. Please refer to http://jb.gg/ide/critical-startup-errors

java.util.concurrent.CompletionException: org.picocontainer.PicoRegistrationException: Key net.ntworld.mergeRequestIntegrationIde.service.ApplicationService duplicated
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:380)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.MainImpl$1.proceed(MainImpl.java:109)
    at com.intellij.ide.b.n.Z.proceed(Z.java:97)
    at com.intellij.ide.b.n.aq.b(aq.java:261)
    at com.intellij.ide.b.n.ag.b(ag.java:642)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.picocontainer.PicoRegistrationException: Key net.ntworld.mergeRequestIntegrationIde.service.ApplicationService duplicated
    at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:112)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerServices(PlatformComponentManagerImpl.kt:271)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerComponents(PlatformComponentManagerImpl.kt:136)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerComponents(PlatformComponentManagerImpl.kt:108)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:114)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
    ... 14 more

-----
JRE 11.0.5+9-b674.2 x86_64 by JetBrains s.r.o
/Users/marti.raudsepp/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.3803.71/IntelliJ IDEA 2020.1 EAP.app/Contents/jbr/Contents/Home
</pre>

Quite annoying first experience for a commercial plugin.

**Comment by turnik** [comment] 2020-01-31 09:20
Looks like, both versions CE and EE installed in your IDE

**Comment by intgr** [comment] 2020-01-31 10:47
Yes, I encountered issue #19 and wanted to see if the EE edition behaves any differently. I didn't think it was necessary to uninstall the other one.

**Comment by edoreld** [comment] 2020-02-03 17:28
What's the use case for having two versions of the plugin installed at the same time?

**Comment by intgr** [comment] 2020-02-03 18:17
There is no use case. Like I said, the CE version of the plugin didn't work for me so I wanted to try out the EE edition to see if that behaves differently.

I did not know keeping the other version would cause issues, so I didn't uninstall it.

A startup crash that disables the application, until I manually locate the IDE settings folder and delete the plugin, is a pretty annoying failure mode.

If it would just avoid loading a conflicting plugin and continue with startup, that would be far better. I don't know if that's something the plugin can do or if it's an IDEA issue.

**Comment by nhat-phan** [comment] 2020-02-07 15:56
The fix is merged to master. In next version, CE & EE version are completely separated and can be installed on the same IDE.

I'll close this one when the next version is released.

**Comment by intgr** [comment] 2020-02-07 18:28
Thank you! Sorry if I came off as confrontational in my original report. I needed the IDE in a hurry and was frustrated that it failed to start.

**Closed** 2020-03-01 20:40 UTC
Labels: Merged - Waiting for being released

**Comment by ma-za-kpe** [comment] 2020-08-06 10:37
java.util.concurrent.CompletionException: org.picocontainer.PicoRegistrationException: Key io.flutter.settings.FlutterSettings duplicated
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
    at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
    at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
    at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:110)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:376)
    at com.a.d.b.b.av.a(av.java:65)
    at com.a.d.b.b.aA.a(aA.java:98)
    at com.a.d.b.b.n.b(n.java:260)
    at com.a.d.b.b.n.a(n.java:122)
    at com.a.d.b.b.o.a(o.java:56)
    at com.intellij.idea.MainImpl.start(MainImpl.java:19)
    at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:303)
    at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:245)
    at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.picocontainer.PicoRegistrationException: Key io.flutter.settings.FlutterSettings duplicated
    at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:119)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:320)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:186)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:93)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
    ... 20 more

-----
JRE 1.8.0_242-release-1644-b01 amd64 by JetBrains s.r.o
C:\Program Files\Android\Android Studio Preview\android-studio\jre\jre

**Comment by ma-za-kpe** [comment] 2020-08-06 10:38
Did you ever find the solution?

**Comment by intgr** [comment] 2020-08-06 11:00
@ma-za-kpe I think this particular issue was fixed in the plugin already. But manually deleting the plugin's files from IntelliJ's folder fixed it for me.

**Comment by ma-za-kpe** [comment] 2020-08-06 11:04
I cannot seem to find the plugin Flutter storm in my plugins folder.

**Comment by Efhemo** [comment] 2020-08-27 14:04
i got this error after installing FL Storm

Internal error. Please refer to https://code.google.com/p/android/issues

java.util.concurrent.CompletionException: org.picocontainer.PicoRegistrationException: Key io.flutter.settings.FlutterSettings duplicated
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
    at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
    at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
    at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:110)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:376)
    at com.a.c.c.d.aw.a(aw.java:65)
    at com.a.c.c.d.aY.a(aY.java:98)
    at com.a.c.c.d.a1.b(a1.java:260)
    at com.a.c.c.d.a1.a(a1.java:122)
    at com.a.c.c.d.aC.a(aC.java:56)
    at com.intellij.idea.MainImpl.start(MainImpl.java:19)
    at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:303)
    at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:245)
    at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.picocontainer.PicoRegistrationException: Key io.flutter.settings.FlutterSettings duplicated
    at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:119)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:320)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:186)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:93)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
    ... 20 more

-----
JRE 1.8.0_242-release-1644-b3-6222593 x86_64 by JetBrains s.r.o
/Applications/Android Studio 4.1 Preview.app/Contents/jre/jdk/Contents/Home/jre

**Comment by youngdevps** [comment] 2020-10-29 16:47
please are located the plugins files of android studio?

**Comment by eEQK** [comment] 2020-11-27 09:24
I had the same issue after installing Flutter Storm: `Key io.flutter.settings.FlutterSettings duplicated`. I couldn't start the IDE anymore, I had to delete plugin manually from IDE dir (not from `.cache`): `~/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.5981.114.plugins`, note that the IDE version will likely be different

In order tor flutter storm to work you have to disable jetbrains' flutter plugin

**Comment by sweetnandha** [comment] 2023-09-07 19:05
I am also facing an issue while installing maven 2 plugin. so that tried lot after i am getting solution may be it will work. its working fine for me.

- Path : `/Users/<Your User Name>/Applications/IntelliJ IDEA Community Edition.app/Contents/bin `
- Inside bin folder you can get repair/restarter exec file.
- execute the file it will show issues
- can remove/disable the plugin manually.
