### ISSUE TITLE
Crash: Already disposed: MessageBus(…)

### ISSUE THREAD

**Issue by dragetd** [nhat-phan/merge-request-integration#98] opened 2020-09-08 05:43 UTC
I had restarted my PC after hibernation and started working on my project again. Not sure if this is related. I got not much info except the stacktrace from IDEA.

If this is not enough to narrow down the problem, then please close this issue!

```
java.lang.Throwable: Already disposed: MessageBus(owner=Project(name=x-x-x, containerState=DISPOSE_COMPLETED, componentStore=/home/draget/x/repos/x-x/x/x-x-x), disposeState= 2)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.intellij.util.messages.impl.MessageBusImpl.checkNotDisposed(MessageBusImpl.java:330)
	at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:32)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:168)
	at com.sun.proxy.$Proxy76.removeReworkWatcher(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.rework.internal.ReworkWatcherImpl.terminate(ReworkWatcherImpl.kt:147)
	at net.ntworld.mergeRequestIntegrationIde.watcher.WatcherManagerImpl$MyTimerTask.run(WatcherManagerImpl.kt:40)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by MaDKaTZe** [comment] 2020-10-29 12:29
I was able to reproduce the issue couple of times now - last one of which happened after opening project in same window. The error was for previously opened project.

**Comment by nhat-phan** [comment] 2021-01-04 21:18
Thank you for reporting, the bug happens because of the MessageBus get disposed when closing a project but rework worker still running and sends message to close a tool window.

**Closed** 2021-01-11 08:35 UTC
Labels: Bug, Merged - Waiting for being released
